name: string_utilities
description: "A set of utility functions and extensions for enhanced string operations in Dart and Flutter."
version: 1.1.1
homepage: "https://github.com/PratikAmonkar/string_utility"
documentation: "https://github.com/PratikAmonkar/string_utility"

example: example/string_utilities_example.dart

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.4.0
    
dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.26.3
